baseURL: https://eloajo.fi # todo: change site url.
title: Eloajo # todo: change site name.
defaultContentLanguage: "fi"
theme: eternity
#googleAnalytics: "" # todo: set your analytics id.
postSections:
  - posts
  - post

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Eloajo tapahtuman sivusto # todo: change default subtitle for your website.
  copyright: Kaikki oikeudet pidätetään. # todo: set your copyright type.
  author: Joonas Koistinen # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        # Sivun kansion nimen mukaisesti
        previous_years: 2
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: change these links.
    #- icon: "far fa-envelope fa-lg"
    #  url: "mailto:jtkoistinen@gmail.com"
    #  landing: true
  homepage: "/eloajo_2023" # homepage link, mostly same with menu.main[0]
  specialPages:
    - main
    - gallery
    - previous_years
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  #plausible: "" # todo: set your plausible id.
  disableRadius: false
  moveIt: true # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: Etusivu
      url: /eloajo_2023/
      weight: 1
    - name: Aiemmat vuodet
      url: /previous_years/
      weight: 2
    - name: Galleria
      url: /tags/gallery/
      weight: 3
