baseURL: http://www.eloajo.fi # todo: change site url.
title: Eloajo # todo: change site name.
defaultContentLanguage: "fi"
theme: eternity
#googleAnalytics: "" # todo: set your analytics id.
postSections:
  - posts
  - post

params:
  image: /images/eloajo-logo.jpg
  logo: eloajo-logo.jpg # todo: add your custom logo to static/
  subtitle: Eloajo tapahtuman sivusto # todo: change default subtitle for your website.
  copyright: Kaikki oikeudet pidätetään. # todo: set your copyright type.
  author: SISU Enduro Ry # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # todo: change these links.
    #- icon: "far fa-envelope fa-lg"
    #  url: "mailto:jtkoistinen@gmail.com"
    #  landing: true
  homepage: "/eloajo_2023" # homepage link, mostly same with menu.main[0]
  specialPages:
    - main
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  #plausible: "" # todo: set your plausible id.
  disableRadius: false
  moveIt: true # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"
menu:
  main:
    - name: Eloajo 2023
      url: /eloajo_2023/
      weight: 1
#    - name: Kuvia aiemmilta vuosilta
#      url: /galleria/
#      weight: 2
